name: es-mapping-creator

on: 
  workflow_dispatch  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'set up go'
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: 'linux build'
      run: GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w"
    
    - name: 'upload linux binary'
      uses: actions/upload-artifact@v2
      with:
        name: es-mapping-creator
        path: es-mapping-creator
        
    - name: 'windows build'
      run: GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w"
    
    - name: 'upload windows binary'
      uses: actions/upload-artifact@v2
      with:
        name: es-mapping-creator.exe
        path: es-mapping-creator
